### ISSUE TITLE
AttributeError with -w or -j

### ISSUE THREAD

**Issue by ldko** [unt-libraries/m2m#7]
If you run the m2m.py script with the sample files and `-w` or `-j` flag, it errors:
```
$ python m2m/m2m.py tests/data/test.csv -m tests/data/test_2_untl.py -w
Processing CSV file tests/data/test.csv with mapping tests/data/test_2_untl.py
Writing record for row 0
Traceback (most recent call last):
  File "m2m/m2m.py", line 243, in <module>
    record.writeTemplateFiles(record.baseDirectory, record.foldername)
AttributeError: 'MetadataRecord' object has no attribute 'baseDirectory'
```

Also, these functions seem to start with a big of redundancy:
```
    def writeTemplateFiles(self, baseDirectory, foldername):
        baseDirectory = baseDirectory
        foldername = foldername
```
```
    def writeJSONFile(self, baseDirectory, foldername, data):
        baseDirectory = baseDirectory
        foldername = foldername
```

**Comment by madhuBayy** [comment]
Do we want to have optional arguments to give `baseDirectory`, `foldername` and have some default values in `setBaseDirectory`, `setFolderName` ?

**Comment by vphill** [comment]
Probably the safest (most expected) thing to do in those situations would be to have m2m error saying that 
that `record.setBaseDirectory` and `record.setFolderName` are required in order to write files.
